### ISSUE TITLE
Rework some vocabulary

### ISSUE THREAD

**Issue by michaelghinrichs** [devlocker/backend#130]
The ToDo component says too much. Let the button do the talking.

Remove the text? Say something different?

<img width="1920" alt="screen shot 2015-08-27 at 9 14 47 am" src="https://cloud.githubusercontent.com/assets/1623740/9528302/aa4f836a-4ca8-11e5-877e-14e164cc0362.png">

**Comment by mcasper** [comment]
ported to frontend
