### ISSUE TITLE
Home page should show installed plugins

### ISSUE THREAD

**Issue by michaelghinrichs** [devlocker/backend#131]
currently, the root page has a list of lockers. Might be interesting to have more info about what plugins are installed in each locker?  The ability to add a description as well might be useful, but might detract from our `simple` design principle 

<img width="1908" alt="screen shot 2015-08-27 at 9 20 50 am" src="https://cloud.githubusercontent.com/assets/1623740/9528372/fb34358c-4ca8-11e5-8e63-197e49b1068d.png">

**Comment by mcasper** [comment]
ported to frontend (sort of)
