### ISSUE TITLE
Color pickers don't indicate status

### ISSUE THREAD

**Issue by michaelghinrichs** [devlocker/backend#132]
<img width="1912" alt="screen shot 2015-08-27 at 9 17 46 am" src="https://cloud.githubusercontent.com/assets/1623740/9528431/43c4ccd0-4ca9-11e5-899c-ac9811166896.png">

**Comment by michaelghinrichs** [comment]
when you click them, it is not obvious what one you are selecting. Look into adding hover state or focus

**Comment by mcasper** [comment]
Ported to frontend
